variables:
  CI_REGISTRY: "registry.gitlab.com/love4src/frontend"

services:
  - docker:20.10.6-dind

build:
  stage: build
  image: docker:20.10.6

  script:
    - docker build --tag "registry.gitlab.com/love4src/frontend:${CI_COMMIT_SHA}" --tag "registry.gitlab.com/love4src/frontend:latest" .
    - docker push "registry.gitlab.com/love4src/frontend:${CI_COMMIT_SHA}"
    - docker push "registry.gitlab.com/love4src/frontend:latest"
  only:
    - main

release:
  stage: deploy
  image: "hashicorp/levant:0.3.0"
  script:
    - levant deploy -address="http://localhost:4646" -var "commit_sha=${CI_COMMIT_SHA}" bitclout-frontend.hcl
  only:
    - main
