image: docker:20.10.6

variables:
  CI_REGISTRY: "registry.gitlab.com/love4src/frontend"

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build --tag $CI_REGISTRY:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY:$CI_COMMIT_SHA
  only:
    - main

release:
  stage: deploy
  image: "hashicorp/levant:0.3.0"
  script:
    - levant deploy -address="http://localhost:4646" -var "commit_sha=$CI_COMMIT_SHA" bitclout-frontend.hcl
  only:
    - main
