variables:
  CI_REGISTRY: "registry.gitlab.com/love4src/frontend"

services:
  - docker:dind

build:
  stage: build
  image: docker:stable
  script:
    - docker build --pull --tag "registry.gitlab.com/love4src/frontend:${CI_COMMIT_SHA}" --tag "registry.gitlab.com/love4src/frontend:latest" .
    - docker login registry.gitlab.com -u gitlab+deploy-token-470767 -p PyiC-v4QGZaGzbD9z8B_
    - docker push "registry.gitlab.com/love4src/frontend:${CI_COMMIT_SHA}"
    - docker push "registry.gitlab.com/love4src/frontend:latest"
  only:
    - main

release:
  stage: deploy
  image: "hashicorp/levant:0.3.0"
  script:
    - levant deploy -address="http://localhost:4646" -var "commit_sha=${CI_COMMIT_SHA}" bitclout-frontend.hcl
  only:
    - main
